# Generated by Django 5.2 on 2025-06-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='interview_date',
        ),
        migrations.AlterField(
            model_name='interviewresponse',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
