# Generated by Django 5.2.9 on 2026-01-08 07:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_candidate_interview_date_candidate_question_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=20)),
                ('number_of_questions', models.IntegerField(default=10)),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ'), ('Descriptive', 'Descriptive'), ('Coding', 'Coding'), ('Voice', 'Voice')], default='Descriptive', max_length=20)),
                ('interview_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(default=60)),
                ('evaluation_weightage', models.JSONField(default=dict)),
                ('enable_emotion_analysis', models.BooleanField(default=True)),
                ('enable_voice_interview', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='question_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=20),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('confidence_level', models.FloatField(blank=True, null=True)),
                ('final_decision', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=20, null=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='EmotionLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('emotion', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.interview')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy_percentage', models.FloatField()),
                ('confidence_level', models.FloatField()),
                ('strengths', models.TextField()),
                ('weak_areas', models.TextField()),
                ('recommendation', models.TextField()),
                ('eye_contact_percentage', models.FloatField(blank=True, null=True)),
                ('speech_fluency_score', models.FloatField(blank=True, null=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.interview')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ'), ('Descriptive', 'Descriptive'), ('Coding', 'Coding'), ('Voice', 'Voice')], max_length=20)),
                ('correct_answer', models.TextField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.interview')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_answer', models.TextField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.questions')),
            ],
        ),
        migrations.CreateModel(
            name='SpeechTranscripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField()),
                ('fluency_score', models.FloatField(blank=True, null=True)),
                ('speech_accuracy', models.FloatField(blank=True, null=True)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.answers')),
            ],
        ),
    ]
