# Generated by Django 5.2.12 on 2026-03-15 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_adminsettings_alter_candidate_question_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionlogs',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.questions'),
        ),
    ]
